/*
 * Copyright (c) 2026 HPMicro
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *
 *
 * Automatically generated by HPM Pinmux Tool
 *
 *
 * Note:
 * PY and PZ IOs: if any SOC pin function needs to be routed to these IOs,
 * besides of IOC, PIOC/BIOC needs to be configured SOC_GPIO_X_xx, so that
 * expected SoC function can be enabled on these IOs.
 */

#ifndef HPM_PINMUX_H
#define HPM_PINMUX_H

#include "hpm_soc.h"

#ifdef __cplusplus
extern "C" {
#endif

void init_jtag_pins(void);
void init_mcan0_pins(void);
void init_pwm0_pins(void);
void init_pwm1_pins(void);
void init_analog_pins(void);
void init_gptmr0_pins(void);
void init_uart0_pins(void);
void init_gpio_pins(void);

void init_pins(void);

/* compatibility wrapper */
void init_uart_pins(UART_Type *ptr);

#ifdef __cplusplus
}
#endif

#endif /* HPM_PINMUX_H */
